language: node_js
node_js:
- 8.9.1
sudo: false
cache:
  directories:
    - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
branches:
  only:
  - master
script:
  - . build.sh