language: node_js
node_js:
- 8.9.1
sudo: false
cache:
  directories:
  - node_modules
  - themes
before_install:
- npm install hexo-cli -g
install:
- npm install
branches:
  only:
  - source
script:
- . theme.sh
- . build.sh
- git config --global user.name "Travis-CI"
- hexo deploy --silent